-- perf.sql -- the shape that makes an importdb-vs-loaddb comparison mean
-- something.
--
-- Four properties the perf case needs, and why:
--
--   * five tables, so `unloaddb --datafile-per-class` writes five object files.
--     A default unloaddb writes ONE, and with one object file --degree has
--     nothing to spread -- neither arm would fan out and the "parallelism held
--     equal" claim would be vacuous.
--   * one table (pf_fact) carrying most of the rows, so the per-row index and
--     foreign-key maintenance the loaddb arm pays is a real cost rather than a
--     rounding error.
--   * a PK, a UNIQUE and a plain secondary index on that dominant table -- three
--     b-trees maintained per inserted row in the loaddb arm, built once in bulk
--     by importdb.
--   * FK edges into pf_dim from every other table, so the loaddb arm also pays a
--     referential check per row while importdb defers the whole edge.
--
-- Row data is generated by gen_perf_rows.sh, not committed.

CREATE TABLE pf_dim (
  dim_id INTEGER PRIMARY KEY,
  code   VARCHAR(16) UNIQUE,
  nm     VARCHAR(40)
);

CREATE TABLE pf_fact (
  fact_id INTEGER PRIMARY KEY,
  dim_id  INTEGER,
  ukey    VARCHAR(24),
  bucket  INTEGER,
  amount  NUMERIC(12,2),
  pad     VARCHAR(48),
  CONSTRAINT fk_pf_fact_dim FOREIGN KEY (dim_id) REFERENCES pf_dim(dim_id)
);

CREATE TABLE pf_side1 (
  id     INTEGER PRIMARY KEY,
  dim_id INTEGER,
  pad    VARCHAR(40),
  CONSTRAINT fk_pf_side1_dim FOREIGN KEY (dim_id) REFERENCES pf_dim(dim_id)
);

CREATE TABLE pf_side2 (
  id     INTEGER PRIMARY KEY,
  dim_id INTEGER,
  pad    VARCHAR(40),
  CONSTRAINT fk_pf_side2_dim FOREIGN KEY (dim_id) REFERENCES pf_dim(dim_id)
);

CREATE TABLE pf_side3 (
  id     INTEGER PRIMARY KEY,
  dim_id INTEGER,
  pad    VARCHAR(40),
  CONSTRAINT fk_pf_side3_dim FOREIGN KEY (dim_id) REFERENCES pf_dim(dim_id)
);

CREATE UNIQUE INDEX u_pf_fact_ukey ON pf_fact(ukey);
CREATE INDEX i_pf_fact_bucket ON pf_fact(bucket);
