#!/usr/bin/env python3
"""Regenerate the README's four animated figures into assets/.

Both figures are written by hand at the level that matters -- geometry, wording,
palette -- but the animation is a few dozen staggered keyframe windows, and
hand-maintaining those in the SVG is how they rot. So the layout arithmetic and
the keyframe table are computed here and the SVGs are output.

Three rules the figures follow, and the reason for each:

  * One cycle for everything. Every animation is CYCLE seconds long and starts
    at 0; an element's moment is encoded as percentages inside its own
    keyframes, never as animation-delay. That makes the whole picture a single
    choreography that loops cleanly instead of a set of independent clocks.
  * The base state is the finished state. Animation only ever moves an element
    from absent to present, so a renderer with no CSS animation -- and a reader
    with prefers-reduced-motion -- gets the complete figure rather than an
    empty stage.
  * Light is the base palette, dark is a media override, for the same reason
    the banner does it that way.

Usage: tools/gen_figures.py [assets-dir]
"""
import math
import os
import sys

CYCLE = 8.0                       # seconds; one full pass plus a pause to read it


def pct(t):
    return round(t / CYCLE * 100.0, 3)


# from-state, to-state, and the element declarations the transform needs
KINDS = {
    "pop":   ("opacity:0;transform:scale(.3)", "opacity:1;transform:none",
              "transform-box:fill-box;transform-origin:50% 50%"),
    "rise":  ("opacity:0;transform:translateY(5px)", "opacity:1;transform:none", ""),
    "growx": ("transform:scaleX(0)", "transform:scaleX(1)",
              "transform-box:fill-box;transform-origin:0% 50%"),
    "growy": ("transform:scaleY(0)", "transform:scaleY(1)",
              "transform-box:fill-box;transform-origin:50% 0%"),
    "fade":  ("opacity:0", "opacity:1", ""),
}


class Anim:
    """Hands out a class per animation window, folding duplicates into one rule."""

    def __init__(self, prefix):
        self.prefix = prefix
        self._kf = {}
        self._cls = {}
        self.kf = []
        self.cls = []

    def win(self, kind, t0, t1):
        """Absent until t0, transitions over t0..t1, then held to the cycle end."""
        src, dst, extra = KINDS[kind]
        p0, p1 = pct(t0), pct(t1)
        head = "0%%{%s}" % src if p0 <= 0 else "0%%,%g%%{%s}" % (p0, src)
        return self._cls_for("%s %g%%,100%%{%s}" % (head, p1, dst), extra)

    def flash(self, t0, t1, ramp=0.06):
        """On for t0..t1 only -- for anything whose resting state is invisible."""
        return self._cls_for(
            "0%%,%g%%{opacity:0} %g%%,%g%%{opacity:1} %g%%,100%%{opacity:0}"
            % (pct(t0), pct(t0 + ramp), pct(t1), pct(t1 + ramp)), "")

    def _cls_for(self, body, extra):
        if body not in self._kf:
            self._kf[body] = "%s%d" % (self.prefix, len(self._kf))
            self.kf.append((self._kf[body], body))
        key = (self._kf[body], extra)
        if key not in self._cls:
            self._cls[key] = "a%d" % len(self._cls)
            decls = "animation:%s %gs linear infinite" % (key[0], CYCLE)
            self.cls.append((self._cls[key], extra + ";" + decls if extra else decls))
        return self._cls[key]

    def css(self):
        out = ["    .%s { %s; }" % c for c in self.cls]
        out.append("    @media (prefers-reduced-motion: reduce)"
                   " { * { animation: none !important; } }")
        out += ["    @keyframes %s { %s }" % k for k in self.kf]
        return "\n".join(out)


class Svg:
    def __init__(self, w, h, title, aria):
        self.w, self.h, self.title, self.aria = w, h, title, aria
        self.body = []

    def add(self, s):
        self.body.append("  " + s)

    def text(self, cls, x, y, s, anchor=None):
        a = ' text-anchor="%s"' % anchor if anchor else ""
        self.add('<text class="%s" x="%g" y="%g"%s>%s</text>' % (cls, x, y, a, s))

    def render(self, style):
        return "\n".join(
            ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d"'
             ' width="%d" height="%d"' % (self.w, self.h, self.w, self.h),
             '     role="img" aria-label="%s">' % self.aria,
             '  <title>%s</title>' % self.title,
             '  <!-- GENERATED by tools/gen_figures.py; edit that, not this. -->',
             style,
             '  <rect class="bg" x="0" y="0" width="%d" height="%d"/>' % (self.w, self.h)]
            + self.body + ['</svg>', ''])


PALETTE = """    /* CUBRID's brand hues, sampled from the official tangram mark. The logo
       palette is tuned for fills, not for 11px text, so text takes darkened
       variants and only fills and strokes get the pure values. */
    .bg    { fill: #ffffff; }
    .ink   { fill: #1D1D1B; }
    .muted { fill: #5b6470; }
    .good  { fill: #00801F; }"""

MONO = 'ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace'
SANS = 'ui-sans-serif, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif'


def font(cls, stack, size, weight=None, extra=""):
    w = " font-weight: %d;" % weight if weight else ""
    return ("    .%s { font-family: %s;\n           font-size: %gpx;%s%s }"
            % (cls, stack, size, w, extra))


# ======================================================================
#  Figure 1 -- the constraint lifecycle, two ways
# ======================================================================
def lifecycle():
    W, H = 900, 382
    A = Anim("l")

    COLS = [138 + 35 * k for k in range(12)]     # the twelve rows being loaded
    ORPHAN = 8                                   # 9th of them: parent key missing
    OX = COLS[ORPHAN]
    BAND_X, BAND_W = 126, 422
    BAR_X, BAR_END = 131, 540
    TAG_X = 556                                  # tags hang outside the bands
    SEP_X, PAN_X, PAN_W, LBL_X = 652, 668, 208, 108

    g = Svg(W, H, "The constraint lifecycle, two ways",
            "The constraint lifecycle, two ways. Schema-first loaddb keeps every "
            "constraint live through the data phase, paying one b-tree write per "
            "row per index -- thirty-six writes for twelve rows -- with "
            "foreign-key checking off, so an orphan row loads clean and exits 0. "
            "CUBRID ImportDB strips the same constraints, streams the rows into "
            "bare heaps and runs three bulk builds afterwards; the foreign-key "
            "build is the check, so it halts at the offending row, withholds that "
            "one constraint, names the row and exits 1.")

    def lane(y0, rowy, bands, title, sub):
        g.text("lane ink", 24, y0, title)
        g.text("sub muted", 24, y0 + 18, sub)
        g.add('<line class="track" x1="%g" y1="%g" x2="%g" y2="%g"/>'
              % (BAND_X, rowy, BAND_X + BAND_W, rowy))
        g.text("bl muted", LBL_X, rowy + 4, "rows", "end")
        for name, by in bands:
            g.add('<rect class="band" x="%g" y="%g" width="%g" height="16" rx="3"/>'
                  % (BAND_X, by, BAND_W))
            g.text("bl muted", LBL_X, by + 11.8, name, "end")

    def rows(rowy, step, hold):
        """The same twelve rows in both lanes -- only the cadence differs."""
        for k, x in enumerate(COLS):
            t = 0.24 + step * k
            g.add('<rect class="tok%s %s" x="%g" y="%g" width="12" height="12" rx="2"/>'
                  % (" bad" if k == ORPHAN else "", A.win("rise", t, t + hold),
                     x - 6, rowy - 6))

    def exit_arrow(rowy, cls, t):
        g.add('<path class="exit %s %s" d="M618,%g H646 M641,%g L646,%g L641,%g"/>'
              % (cls, A.win("fade", t, t + 0.2), rowy, rowy - 4, rowy, rowy + 4))

    def panel(y, kind, head, lines, t):
        g.add('<g class="%s">' % A.win("fade", t, t + 0.3))
        g.add('<rect class="pan-%s" x="%g" y="%g" width="%g" height="104" rx="6"/>'
              % (kind, PAN_X, y, PAN_W))
        g.text("res %s" % kind, PAN_X + 16, y + 24, head)
        for i, line in enumerate(lines):
            g.text("note muted", PAN_X + 16, y + 43 + i * 18, line)
        g.add('</g>')

    # --- lane A: the hand-scripted loaddb path -------------------------
    BA = [("PK", 86), ("UNIQUE", 108), ("FK", 130)]
    lane(30, 68, BA, "loaddb &#183; schema first",
         "every constraint live for the whole data phase")
    g.text("tag bad", TAG_X, BA[2][1] + 11.6, "checking OFF")
    g.add('<rect class="head hA" x="130" y="58" width="1.6" height="92" rx="0.8"/>')

    rows(68, 0.31, 0.16)
    for k, x in enumerate(COLS):                 # one b-tree write per row, per index
        w = A.win("pop", 0.24 + 0.31 * k + 0.07, 0.24 + 0.31 * k + 0.24)
        for _, by in BA:
            g.add('<circle class="write %s" cx="%g" cy="%g" r="3"/>' % (w, x, by + 8))

    t_orphan = 0.24 + 0.31 * ORPHAN
    g.add('<g class="%s">' % A.win("fade", t_orphan, t_orphan + 0.2))
    g.text("orph bad", OX, 47, "orphan", "middle")
    g.add('<line class="lead bad-s" x1="%g" y1="51" x2="%g" y2="59"/>' % (OX, OX))
    g.add('</g>')

    exit_arrow(68, "bad-s", 3.95)
    g.text("note ink", 24, 170, "36 per-row b-tree writes for 12 rows &#8212; and "
                                "FOREIGN KEY checking is off for all of them.")
    panel(48, "bad", "The orphan loaded.",
          ["exit 0, nothing reported.", "The FK sits in the catalog",
           "and the data violates it."], 4.05)

    # --- lane B: CUBRID ImportDB ---------------------------------------
    g.add('<line class="sep" x1="%g" y1="20" x2="%g" y2="362"/>' % (SEP_X, SEP_X))
    g.add('<line class="divider" x1="24" y1="186" x2="640" y2="186"/>')
    g.add('<line class="divider" x1="664" y1="186" x2="876" y2="186"/>')

    BB = [("PK", 282), ("UNIQUE", 304), ("FK", 326)]
    lane(226, 264, BB, "CUBRID ImportDB &#183; strip, load, build",
         "the same constraints stripped and held; the rows go into bare heaps")
    g.add('<rect class="head hB" x="130" y="254" width="1.6" height="90" rx="0.8"/>')
    rows(264, 0.105, 0.12)
    exit_arrow(264, "good-s", 1.55)

    for (_, by), t0, end in ((BB[0], 1.60, BAR_END), (BB[1], 2.20, BAR_END),
                             (BB[2], 2.85, OX)):
        g.add('<rect class="build %s" x="%g" y="%g" width="%g" height="9" rx="2"/>'
              % (A.win("growx", t0, t0 + 0.55), BAR_X, by + 3.5, end - BAR_X))

    # the FK build is the check, so it stops under the row that failed it
    g.add('<rect class="rest %s" x="%g" y="%g" width="%g" height="9" rx="2"/>'
          % (A.win("fade", 3.45, 3.6), OX, BB[2][1] + 3.5, BAR_END - OX))
    g.text("tag muted %s" % A.win("fade", 3.45, 3.65), TAG_X, BB[2][1] + 11.6,
           "not built")
    g.add('<line class="drop bad-s %s" x1="%g" y1="272" x2="%g" y2="322"/>'
          % (A.win("fade", 3.40, 3.62), OX, OX))
    cy = BB[2][1] + 8
    g.add('<g class="%s">' % A.win("pop", 3.40, 3.58))
    g.add('<circle class="halo" cx="%g" cy="%g" r="7"/>' % (OX, cy))
    g.add('<path class="xmark bad-s" d="M%g,%g L%g,%g M%g,%g L%g,%g"/>'
          % (OX - 3.4, cy - 3.4, OX + 3.4, cy + 3.4,
             OX + 3.4, cy - 3.4, OX - 3.4, cy + 3.4))
    g.add('</g>')

    g.text("note ink", 24, 364, "3 bulk builds over the finished heaps &#8212; and the "
                                'FOREIGN KEY build <tspan class="good">is</tspan> the check.')
    panel(244, "good", "The FK is withheld.",
          ["exit 1, and every offending", "row is named in",
           "importdb.exceptions."], 3.60)

    style = """  <style>
%(palette)s
    .bad   { fill: #C4141E; }
    .bad-s  { stroke: #C4141E; }
    .good-s { stroke: #00801F; }

    .band  { fill: #f4f6f8; stroke: #e2e6eb; stroke-width: 1; }
    .track { stroke: #e2e6eb; stroke-width: 1; }
    .tok   { fill: #6a7684; }
    .tok.bad { fill: #E23B45; }
    .write { fill: #E07C00; }
    .build { fill: #12A03B; }
    .rest  { fill: none; stroke: #b8c0c9; stroke-width: 1; stroke-dasharray: 3 3; }
    .head  { fill: #0091F8; opacity: 0; }
    .halo  { fill: #ffffff; }
    .xmark { fill: none; stroke-width: 2; stroke-linecap: round; }
    .lead, .drop { fill: none; stroke-width: 1; stroke-dasharray: 2 2.4; }
    .exit  { fill: none; stroke-width: 1.6; stroke-linecap: round; stroke-linejoin: round; }
    .sep     { stroke: #e2e6eb; stroke-width: 1; }
    .divider { stroke: #e2e6eb; stroke-width: 1; stroke-dasharray: 3 3; }
    .pan-bad  { fill: #fff5f5; stroke: #E23B45; stroke-width: 1.3; }
    .pan-good { fill: #f2fdf5; stroke: #12A03B; stroke-width: 1.3; }

    @media (prefers-color-scheme: dark) {
      .bg    { fill: #0d1117; }
      .ink   { fill: #e9edf2; }
      .muted { fill: #98a1ad; }
      .good  { fill: #3CE066; }
      .bad   { fill: #FF6A73; }
      .bad-s  { stroke: #FF6A73; }
      .good-s { stroke: #3CE066; }
      .band  { fill: #161b22; stroke: #2b313a; }
      .track { stroke: #2b313a; }
      .tok   { fill: #8b96a5; }
      .tok.bad { fill: #FF6A73; }
      .write { fill: #FFAE00; }
      .build { fill: #3CE066; }
      .rest  { stroke: #4a525c; }
      .halo  { fill: #0d1117; }
      .sep, .divider { stroke: #2b313a; }
      .pan-bad  { fill: #241516; stroke: #FF6A73; }
      .pan-good { fill: #0c2113; stroke: #3CE066; }
    }

%(fonts)s

    /* The two playheads are the only hand-written keyframes: each sweeps its own
       lane at that lane's cadence -- 0.31s per row against 0.105s. */
    .hA { animation: headA %(c)gs linear infinite; }
    .hB { animation: headB %(c)gs linear infinite; }
    @keyframes headA {
      0%%,3.1%%    { opacity: 0; transform: translateX(0); }
      3.9%%        { opacity: .7; transform: translateX(8px); }
      46.5%%       { opacity: .7; transform: translateX(393px); }
      48%%,100%%   { opacity: 0; transform: translateX(400px); }
    }
    @keyframes headB {
      0%%,3.1%%    { opacity: 0; transform: translateX(0); }
      3.9%%        { opacity: .7; transform: translateX(8px); }
      18.1%%       { opacity: .7; transform: translateX(393px); }
      19.5%%,100%% { opacity: 0; transform: translateX(400px); }
    }
%(anim)s
  </style>""" % {"c": CYCLE, "palette": PALETTE, "anim": A.css(),
                  "fonts": "\n".join([font("lane", MONO, 13.5, 700),
                                      font("bl", MONO, 10.5, 600),
                                      font("tag", SANS, 9.5, 600, " letter-spacing: .2px;"),
                                      font("orph", SANS, 9.5, 700),
                                      font("sub", SANS, 11),
                                      font("note", SANS, 11.5),
                                      font("res", SANS, 12.5, 700)])}
    return g.render(style)


# ======================================================================
#  Figure 2 -- the ten phases, and where the time goes
# ======================================================================
# share of a 3.93M-row run; docs/performance.md, 34.93 s total
PHASES = [("Discover", 0.001, None), ("Define", 0.001, None), ("Graph", 0.001, None),
          ("Plan", 0.001, None), ("Strip", 0.001, None), ("Load", 0.173, "17%"),
          ("Rebuild", 0.293, "29%"), ("FK define", 0.514, "51%"),
          ("Stats", 0.016, None), ("Triggers", 0.001, None)]
GROUP = (4, 7)                    # Strip .. FK define -- the shape that matters


def phases():
    W, H = 900, 220
    A = Anim("p")
    BOX_W, PITCH, X0, BOX_Y, BOX_H = 78, 86, 24, 56, 48
    AXIS_Y, BAR_MAX, BAR_W, RATE = 124, 44.0, 26, 20.0

    def bx(k):
        return X0 + PITCH * k

    def cx(k):
        return bx(k) + BOX_W / 2.0

    # A bar's height is its phase's time, and every bar rises at RATE px/s -- so
    # the dwell is the height, which makes the pacing itself the measurement.
    tall = max(s for _, s, _ in PHASES)
    h = [max(1.2, s / tall * BAR_MAX) for _, s, _ in PHASES]
    dwell = [max(0.20, x / RATE) for x in h]
    start, t = [], 0.30
    for d in dwell:
        start.append(t)
        t += d
    end = [start[i] + dwell[i] for i in range(len(PHASES))]

    g = Svg(W, H, "The ten phases, and where the time goes",
            "The ten phases of an importdb run -- Discover, Define, Graph, Plan, "
            "Strip, Load, Rebuild, FK define, Stats, Triggers -- with the middle "
            "four marked as the shape that matters: strip the constraints, load "
            "into bare heaps, build afterwards. Below the rail, each phase's "
            "measured share of a 3.93 million row run: Load 17 percent, Rebuild "
            "29 percent, FK define 51 percent, and every other phase under a "
            "second.")

    g.text("hdr ink", 24, 22, "importdb &#183; one command, ten phases")

    gx0, gx1 = bx(GROUP[0]) - 7, bx(GROUP[1]) + BOX_W + 7
    g.add('<rect class="grp" x="%g" y="50" width="%g" height="62" rx="6"/>' % (gx0, gx1 - gx0))
    g.text("gl good", (gx0 + gx1) / 2.0, 44, "strip, load bare, build after", "middle")
    g.text("gl muted", 876, 44, "Triggers last &#183; nothing fires during the load", "end")

    # chevrons rather than a rail: a line behind the boxes shows through only in
    # the 8px gaps, and a path owes nothing to whether a font has an arrow
    for k in range(len(PHASES) - 1):
        x = bx(k) + BOX_W + (PITCH - BOX_W) / 2.0
        g.add('<path class="chev" d="M%g,75.5 L%g,80 L%g,84.5"/>' % (x - 2, x + 2, x - 2))

    for k in range(len(PHASES)):
        g.add('<rect class="st" x="%g" y="%g" width="%g" height="%g" rx="5"/>'
              % (bx(k), BOX_Y, BOX_W, BOX_H))
    for k in range(len(PHASES)):
        done = A.win("fade", start[k], start[k] + 0.12)
        g.add('<rect class="done %s" x="%g" y="%g" width="%g" height="%g" rx="5"/>'
              % (done, bx(k), BOX_Y, BOX_W, BOX_H))
        g.add('<rect class="edge %s" x="%g" y="%g" width="3.5" height="%g" rx="1.6"/>'
              % (done, bx(k), BOX_Y, BOX_H))
        g.add('<rect class="hot %s" x="%g" y="%g" width="%g" height="%g" rx="5"/>'
              % (A.flash(start[k], end[k]), bx(k) - 1, BOX_Y - 1, BOX_W + 2, BOX_H + 2))
    for k, (name, _, _) in enumerate(PHASES):
        g.text("ph ink", cx(k), 79, name, "middle")
        g.text("ord muted", cx(k), 94, str(k + 1), "middle")

    g.add('<line class="axis" x1="24" y1="%g" x2="876" y2="%g"/>' % (AXIS_Y, AXIS_Y))
    for k in range(len(PHASES)):
        g.add('<rect class="bar %s" x="%g" y="%g" width="%g" height="%g" rx="1.5"/>'
              % (A.win("growy", start[k], end[k]), cx(k) - BAR_W / 2.0, AXIS_Y, BAR_W, h[k]))
    for k, (_, _, label) in enumerate(PHASES):
        if label:
            g.text("pctl ink %s" % A.win("fade", end[k], end[k] + 0.2),
                   cx(k), 182, label, "middle")

    g.text("note muted", 24, 204,
           "Bars are the measured share of a 3.93M-row run. Every bar rises at the "
           "same rate, so a bar&#8217;s height is the time that phase took.")

    style = """  <style>
%s
    .chev { fill: none; stroke: #b9c1ca; stroke-width: 1.5; stroke-linecap: round; stroke-linejoin: round; }
    .axis { stroke: #dfe3e8; stroke-width: 1; }
    .st   { fill: #ffffff; stroke: #dfe3e8; stroke-width: 1.2; }
    .done { fill: #f1fbf4; stroke: #9fdeb4; stroke-width: 1.2; }
    .edge { fill: #12A03B; }
    .hot  { fill: none; stroke: #12A03B; stroke-width: 1.8; opacity: 0; }
    .grp  { fill: none; stroke: #12A03B; stroke-width: 1.1; stroke-dasharray: 4 3; }
    .bar  { fill: #12A03B; }

    @media (prefers-color-scheme: dark) {
      .bg    { fill: #0d1117; }
      .ink   { fill: #e9edf2; }
      .muted { fill: #98a1ad; }
      .good  { fill: #3CE066; }
      .chev { stroke: #4a525c; }
      .axis { stroke: #2b313a; }
      .st   { fill: #14181e; stroke: #2b313a; }
      .done { fill: #0e1f14; stroke: #2c6b41; }
      .edge { fill: #3CE066; }
      .hot  { stroke: #3CE066; }
      .grp  { stroke: #2c6b41; }
      .bar  { fill: #3CE066; }
    }

%s
%s
  </style>""" % (PALETTE, "\n".join([font("hdr", MONO, 12.5, 700),
                                     font("ph", SANS, 11.5, 600),
                                     font("ord", MONO, 9),
                                     font("gl", SANS, 10.5, 600),
                                     font("pctl", SANS, 11.5, 700),
                                     font("note", SANS, 11.5)]), A.css())
    return g.render(style)


# ======================================================================
#  Figure 3 -- the load order is read from the schema, not typed
# ======================================================================
# The shop fixture's real graph and schedule, from docs/output.md: five
# classes, three FK edges child -> parent, one serial, three level sets and
# seventeen terminal tasks. The cycle in the note is tests/fixtures/fkcycle.sql.
GNODE = {                          # name: (x, y) of the chip's top-left
    "region": (44, 142), "product": (44, 176), "audit_log": (44, 210),
    "customer": (196, 142), "orders": (330, 176),
}
GFK = [("customer", "region"), ("orders", "customer"), ("orders", "product")]
LEVELS = [["audit_log", "product", "region"], ["customer"], ["orders"]]
DUMPFILES = [("shop_schema", 92), ("shop_objects", 100), ("shop_indexes", 100)]


def plan():
    W, H = 900, 372
    A = Anim("n")
    CW, CH = 76, 20                # a class chip
    LX, LW = 530, 346              # the level bands

    g = Svg(W, H, "The load order is read from the schema, not typed",
            "How importdb derives the load order. Discover finds the dump's "
            "prefix, its layout and each file's role; Define replays the dump's "
            "own DDL into the target; Graph reads the target catalog for five "
            "classes, three foreign-key edges child to parent and one serial; "
            "Plan layers that graph into three level sets -- audit_log, product "
            "and region first, then customer, then orders -- and seventeen "
            "terminal tasks. The hand-scripted loaddb path has no such step: "
            "its three invocations are ordered by whoever types them, and a "
            "cycle it cannot order at all.")

    g.text("hdr ink", 24, 22,
           "importdb &#183; the load order is read from the schema, not typed")

    def chip(x, y, w, h, name, cls, anim, fcls="cn ink"):
        g.add('<rect class="%s %s" x="%g" y="%g" width="%g" height="%g" rx="4"/>'
              % (cls, anim, x, y, w, h))
        g.text("%s %s" % (fcls, anim), x + w / 2.0, y + h / 2.0 + 3.7, name, "middle")

    def chev(x, y, anim):
        g.add('<path class="cv %s" d="M%g,%g L%g,%g L%g,%g"/>'
              % (anim, x - 3, y - 5, x + 3, y, x - 3, y + 5))

    # --- row A: discover, then define ---------------------------------
    g.text("sec muted", 24, 46, "1 &#183; DISCOVER")
    g.text("sec muted", 470, 46, "2 &#183; DEFINE")

    g.text("cmd muted", 24, 72, "dump/")
    x = 76
    for k, (name, w) in enumerate(DUMPFILES):
        chip(x, 58, w, 20, name, "file", A.win("rise", 0.20 + 0.25 * k, 0.20 + 0.25 * k + 0.2))
        x += w + 6
    g.text("tag good %s" % A.win("fade", 1.00, 1.20), 24, 96,
           "prefix &#8216;shop&#8217; &#183; single-file layout &#183; roles resolved")

    chev(452, 68, A.win("fade", 1.15, 1.3))
    chip(470, 58, 128, 20, "define &#8216;shoptgt&#8217;", "tgt",
         A.win("rise", 1.20, 1.45), "cn good")
    g.text("cap muted %s" % A.win("fade", 1.35, 1.55), 610, 72,
           "from the dump&#8217;s own DDL &#8212; users, hashes, grants")
    g.text("cap muted", 470, 96,
           "Nothing above is passed on the command line.")

    g.add('<line class="divider" x1="24" y1="106" x2="876" y2="106"/>')

    # --- row B: the graph, and the layering of it ----------------------
    g.text("sec muted", 24, 122, "3 &#183; GRAPH &#8212; READ FROM THE CATALOG")
    g.text("sec muted", 510, 122, "4 &#183; PLAN &#8212; DERIVED")

    for k, (name, (nx, ny)) in enumerate(sorted(GNODE.items())):
        chip(nx, ny, CW, CH, name, "node", A.win("pop", 1.70 + 0.11 * k, 1.70 + 0.11 * k + 0.2))
    g.text("tag muted %s" % A.win("fade", 2.20, 2.4), 126, 224, "serial")

    def edge(a, b, anim):
        """child -> parent, the head at the parent end; parent loads first."""
        (ax, ay), (bx, by) = GNODE[a], GNODE[b]
        x0, y0 = ax + (0 if ax < bx else CW), ay + CH / 2.0
        x1, y1 = bx + (CW + 5 if ax > bx else -5), by + CH / 2.0
        if a == "orders" and b == "product":       # route under customer
            y0 = y1 = ay + CH / 2.0
        dx, dy = x1 - x0, y1 - y0
        n = math.hypot(dx, dy) or 1.0
        ux, uy = dx / n, dy / n
        hx, hy = x1 - ux * 8, y1 - uy * 8
        g.add('<path class="ed %s" d="M%g,%g L%g,%g"/>' % (anim, x0, y0, hx, hy))
        g.add('<path class="eh %s" d="M%g,%g L%g,%g L%g,%g Z"/>'
              % (anim, x1, y1, hx - uy * 3.8, hy + ux * 3.8, hx + uy * 3.8, hy - ux * 3.8))

    for k, (child, parent) in enumerate(GFK):
        edge(child, parent, A.win("fade", 2.55 + 0.28 * k, 2.55 + 0.28 * k + 0.22))
    g.text("cap muted %s" % A.win("fade", 3.45, 3.65), 24, 250,
           "5 node(s), 3 FK edge(s), 0 inheritance edge(s), 1 serial &#183; "
           "arrows are child -&gt; parent")

    chev(492, 118, A.win("fade", 3.60, 3.75))

    for i, level in enumerate(LEVELS):
        y = 140 + i * 34
        t = 3.90 + 0.55 * i
        g.add('<rect class="band %s" x="%g" y="%g" width="%g" height="26" rx="5"/>'
              % (A.win("growx", t, t + 0.35), LX, y, LW))
        g.text("lvl good %s" % A.win("fade", t, t + 0.2), 514, y + 17, "L%d" % i, "end")
        for k, name in enumerate(level):
            chip(LX + 10 + k * (CW + 8), y + 4, CW, 18, name, "node",
                 A.win("pop", t + 0.22 + 0.1 * k, t + 0.42 + 0.1 * k))
    g.text("cap muted %s" % A.win("fade", 5.55, 5.75), 510, 250,
           "3 level(s), 17 terminal task(s) &#8212; every level is parallel-eligible")

    g.add('<line class="divider" x1="24" y1="266" x2="876" y2="266"/>')

    # --- row C: what the operator types, either way --------------------
    g.text("lane bad", 24, 290, "loaddb &#183; the order is yours to get right")
    for k, f in enumerate(("-s shop_schema&#160;", "-d shop_objects",
                           "-i shop_indexes")):
        g.text("cmd ink %s" % A.win("rise", 6.10 + 0.18 * k, 6.10 + 0.18 * k + 0.2),
               24, 312 + k * 17, "cubrid loaddb -C -u dba %s shoptgt" % f)

    g.text("lane good", 510, 290, "CUBRID ImportDB &#183; one command")
    g.text("cmd ink %s" % A.win("rise", 6.80, 7.0), 510, 312,
           "cubrid-importdb -u dba shoptgt dump/")
    for k, line in enumerate((
            "A cycle is a non-event: cy_a and cy_b reference each other, so no",
            "load order satisfies both FKs. Both land in L0, because FK definition",
            "is deferred for every edge.")):
        g.text("note muted %s" % A.win("fade", 7.10 + 0.12 * k, 7.30 + 0.12 * k),
               510, 331 + k * 15, line)

    style = """  <style>
%(palette)s
    .bad   { fill: #C4141E; }

    .file { fill: #f4f6f8; stroke: #cfd6de; stroke-width: 1; }
    .tgt  { fill: #f2fdf5; stroke: #9fdeb4; stroke-width: 1.2; }
    .node { fill: #ffffff; stroke: #b9c4d0; stroke-width: 1.2; }
    .band { fill: #f1fbf4; stroke: #9fdeb4; stroke-width: 1.2; }
    .ed   { fill: none; stroke: #0091F8; stroke-width: 1.4; }
    .eh   { fill: #0091F8; }
    .cv   { fill: none; stroke: #12A03B; stroke-width: 1.8;
            stroke-linecap: round; stroke-linejoin: round; }
    .divider { stroke: #e2e6eb; stroke-width: 1; stroke-dasharray: 3 3; }

    @media (prefers-color-scheme: dark) {
      .bg    { fill: #0d1117; }
      .ink   { fill: #e9edf2; }
      .muted { fill: #98a1ad; }
      .good  { fill: #3CE066; }
      .bad   { fill: #FF6A73; }
      .file { fill: #161b22; stroke: #39414c; }
      .tgt  { fill: #0e1f14; stroke: #2c6b41; }
      .node { fill: #14181e; stroke: #414b58; }
      .band { fill: #0e1f14; stroke: #2c6b41; }
      .ed   { stroke: #4DB2FF; }
      .eh   { fill: #4DB2FF; }
      .cv   { stroke: #3CE066; }
      .divider { stroke: #2b313a; }
    }

%(fonts)s
%(anim)s
  </style>""" % {"palette": PALETTE, "anim": A.css(),
                 "fonts": "\n".join([font("hdr", MONO, 12.5, 700),
                                     font("sec", SANS, 9.5, 700, " letter-spacing: .7px;"),
                                     font("lane", MONO, 12, 700),
                                     font("cn", MONO, 10.5, 600),
                                     font("lvl", MONO, 11, 700),
                                     font("cmd", MONO, 10.5),
                                     font("tag", SANS, 9.5, 600, " letter-spacing: .2px;"),
                                     font("cap", SANS, 10.5),
                                     font("note", SANS, 11)])}
    return g.render(style)


# ======================================================================
#  Figure 4 -- the statistics are computed last, and the run shows it
# ======================================================================
# Left: when the per-class statistics are computed, in each path. loaddb runs
# them at the end of the OBJECT load (load_db.c, suppressible with
# --no-statistics); its index phase afterwards refreshes only the _db_index and
# _db_index_key CATALOG statistics, so the class statistics it computed predate
# the secondary indexes. importdb passes --no-statistics to every loader child
# (import_load.cpp) and schedules STATS per class after that class's rebuilds
# and the index build (import_plan.cpp phase 4). Right: both surfaces verbatim
# from docs/output.md.
LANE_A = [("-s schema", 84), ("-d objects", 92), ("-i indexes", 92)]
LANE_B = [("load --no-statistics", 124), ("rebuild + index", 96),
          ("FK define", 66), ("STATS", 56)]


def stats():
    W, H = 900, 360
    A = Anim("s")
    SEP, RX, RW = 456, 476, 400

    g = Svg(W, H, "The statistics are computed last, and the run shows it",
            "When the per-class statistics are computed, and what the run "
            "prints. In the hand-scripted loaddb path they are computed at the "
            "end of the object load, and the index file loaded afterwards "
            "refreshes only the _db_index and _db_index_key catalog statistics "
            "-- so the class statistics predate the secondary indexes. importdb "
            "passes --no-statistics to every loader child and schedules STATS "
            "per class after that class's rebuilds and the index build, so the "
            "statistics see the finished table. On the right, the two surfaces "
            "the run shows: a progress block redrawn in place with per-file "
            "offsets, and the phase lines that scroll under it, ending in the "
            "consolidated report.")

    g.text("hdr ink", 24, 22,
           "importdb &#183; the statistics are computed last, and the run shows it")
    g.add('<line class="sep" x1="%g" y1="34" x2="%g" y2="%g"/>' % (SEP, SEP, H - 14))

    def seg(x, y, w, label, cls, anim, h=22):
        g.add('<rect class="%s %s" x="%g" y="%g" width="%g" height="%g" rx="4"/>'
              % (cls, anim, x, y, w, h))
        g.text("sg ink %s" % anim, x + w / 2.0, y + h / 2.0 + 3.6, label, "middle")

    def lane(x0, y, segs, t0, cls, step=0.38):
        out, x = [], x0
        for k, (label, w) in enumerate(segs):
            t = t0 + step * k
            seg(x, y, w, label, cls, A.win("growx", t, t + 0.3))
            out.append((x, x + w, t + 0.3))
            x += w + 6
        return out

    def pin(x, y, ytxt, lines, cls, t, anchor=24):
        a = A.win("pop", t, t + 0.22)
        g.add('<circle class="%s %s" cx="%g" cy="%g" r="5.5"/>' % (cls, a, x, y))
        f = A.win("fade", t + 0.1, t + 0.3)
        g.add('<path class="lead %s" d="M%g,%g V%g H%g"/>'
              % (f, x, y + 7, ytxt - 13, anchor + 2))
        for k, line in enumerate(lines):
            g.text("cap %s %s" % (cls.replace("pin", "txt"), f),
                   anchor, ytxt + k * 15, line)

    # --- left: when the statistics are computed ------------------------
    g.text("sec muted", 24, 46, "WHEN THE PER-CLASS STATISTICS ARE COMPUTED")

    g.text("lane bad", 24, 74, "loaddb &#183; schema first")
    a = lane(24, 84, LANE_A, 0.30, "seg-a")
    pin(a[1][1] - 10, 84, 124,
        ["Computed here, at the end of the object load",
         "&#8212; STATS_WITH_SAMPLING over the loaded classes."],
        "pin-bad", 1.45)
    g.text("cap muted %s" % A.win("fade", 1.95, 2.15), 24, 160,
           "Then the index file runs. It refreshes _db_index and _db_indexkey")
    g.text("cap muted %s" % A.win("fade", 2.05, 2.25), 24, 175,
           "&#8212; the CATALOG statistics &#8212; and nothing per class.")
    g.text("cap bad %s" % A.win("fade", 2.35, 2.55), 24, 196,
           "So the class statistics predate the secondary indexes.")

    g.text("lane good", 24, 234, "CUBRID ImportDB")
    b = lane(24, 244, LANE_B, 2.75, "seg-b", 0.34)
    pin(b[3][1] - 10, 244, 284,
        ["Deferred by --no-statistics on every loader child,",
         "then scheduled per class as a terminal task:"],
        "pin-good", 3.95)
    g.text("tl ink %s" % A.win("rise", 4.35, 4.55), 24, 314,
           "#12 STATS audit_log&#160;&#160; [after #0, #8]")
    g.text("cap good %s" % A.win("fade", 4.75, 4.95), 24, 334,
           "#8 is the index build &#8212; the statistics see the finished table.")

    # --- right: and the run shows it ----------------------------------
    g.text("sec muted", RX, 46, "AND THE RUN SHOWS IT")

    g.add('<rect class="card" x="%g" y="58" width="%g" height="88" rx="6"/>' % (RX, RW))
    g.text("term ink %s" % A.win("fade", 0.35, 0.55), RX + 12, 76,
           "importdb&#160;&#160;tuitgt")
    g.text("term muted %s" % A.win("fade", 0.35, 0.55), RX + RW - 12, 76,
           "load&#160;&#160;[6/10]&#160;&#160;00:00", "end")

    def bar(x, y, w, frac, anim, h=8):
        g.add('<rect class="trk" x="%g" y="%g" width="%g" height="%g" rx="4"/>' % (x, y, w, h))
        g.add('<rect class="fil %s" x="%g" y="%g" width="%g" height="%g" rx="4"/>'
              % (anim, x, y, w * frac, h))

    bar(RX + 12, 86, 200, 0.23, A.win("growx", 0.50, 1.00))
    g.text("term ink %s" % A.win("fade", 0.95, 1.15), RX + 220, 94, "23%")
    g.text("term muted %s" % A.win("fade", 0.95, 1.15), RX + RW - 12, 94,
           "0/4 done &#183; 2 loading", "end")
    for k, (name, frac, size, t) in enumerate((("customer", 0.85, "2 MB", 0.85),
                                               ("orders", 0.17, "18 MB", 1.05))):
        y = 112 + k * 17
        g.text("tl muted %s" % A.win("fade", t, t + 0.2), RX + 24, y + 7, name)
        bar(RX + 96, y, 180, frac, A.win("growx", t, t + 0.55), 7)
        g.text("tl muted %s" % A.win("fade", t + 0.5, t + 0.7), RX + RW - 12, y + 7,
               size, "end")
    g.text("cap muted %s" % A.win("fade", 1.75, 1.95), RX, 162,
           "Redrawn in place. The per-file offsets are read out of")
    g.text("cap muted %s" % A.win("fade", 1.85, 2.05), RX, 177,
           "/proc/&lt;pid&gt;/fdinfo, so the bars are measured, not estimated.")

    g.add('<rect class="card" x="%g" y="198" width="%g" height="118" rx="6"/>' % (RX, RW))
    LINES = [("importdb: rebuilt 8 constraint(s), built 2 index(es).", "term muted", 5.20),
             ("importdb: defined 3 FK(s) on &#8216;shoptgt&#8217;.", "term muted", 5.45),
             ("importdb: updated statistics on 5 class(es).", "term good", 5.70),
             ("importdb: &#8216;shoptgt&#8217; import COMPLETE &#8212; 5 class(es)",
              "term ink", 6.10),
             ("  done, 0 skipped, 0 FK(s) withheld; 3008 row(s).", "term ink", 6.25)]
    for k, (line, cls, t) in enumerate(LINES):
        g.text("%s %s" % (cls, A.win("rise", t, t + 0.2)), RX + 12, 220 + k * 19, line)
    g.text("cap muted %s" % A.win("fade", 6.60, 6.80), RX, 334,
           "The lines scroll under the block. Both are off whenever stdout")
    g.text("cap muted %s" % A.win("fade", 6.70, 6.90), RX, 349,
           "is not a terminal &#8212; a pipe or a CI log gets the plain output.")

    style = """  <style>
%(palette)s
    .bad   { fill: #C4141E; }

    .seg-a { fill: #fff5f5; stroke: #e8b4b7; stroke-width: 1.1; }
    .seg-b { fill: #f1fbf4; stroke: #9fdeb4; stroke-width: 1.1; }
    .pin-bad  { fill: #C4141E; }
    .pin-good { fill: #12A03B; }
    .txt-bad  { fill: #C4141E; }
    .txt-good { fill: #00801F; }
    .lead  { fill: none; stroke: #b8c0c9; stroke-width: 1; stroke-dasharray: 2 2.4; }
    .card  { fill: #f7f9fb; stroke: #dfe3e8; stroke-width: 1.1; }
    .trk   { fill: #e2e6eb; }
    .fil   { fill: #12A03B; }
    .sep   { stroke: #e2e6eb; stroke-width: 1; }

    @media (prefers-color-scheme: dark) {
      .bg    { fill: #0d1117; }
      .ink   { fill: #e9edf2; }
      .muted { fill: #98a1ad; }
      .good  { fill: #3CE066; }
      .bad   { fill: #FF6A73; }
      .seg-a { fill: #241516; stroke: #7a3b40; }
      .seg-b { fill: #0e1f14; stroke: #2c6b41; }
      .pin-bad  { fill: #FF6A73; }
      .pin-good { fill: #3CE066; }
      .txt-bad  { fill: #FF6A73; }
      .txt-good { fill: #3CE066; }
      .lead  { stroke: #4a525c; }
      .card  { fill: #14181e; stroke: #2b313a; }
      .trk   { fill: #2b313a; }
      .fil   { fill: #3CE066; }
      .sep   { stroke: #2b313a; }
    }

%(fonts)s
%(anim)s
  </style>""" % {"palette": PALETTE, "anim": A.css(),
                 "fonts": "\n".join([font("hdr", MONO, 12.5, 700),
                                     font("sec", SANS, 9.5, 700, " letter-spacing: .7px;"),
                                     font("lane", MONO, 12, 700),
                                     font("sg", SANS, 10, 600),
                                     font("tl", MONO, 9.5),
                                     font("term", MONO, 10),
                                     font("cap", SANS, 10.5)])}
    return g.render(style)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), os.pardir, "assets")
    for name, svg in (("lifecycle", lifecycle()), ("phases", phases()),
                      ("plan", plan()), ("stats", stats())):
        path = os.path.join(out, name + ".svg")
        with open(path, "w") as f:
            f.write(svg)
        print("%s  %d bytes" % (path, len(svg)))


if __name__ == "__main__":
    main()
