# Generated by tools/gen_engine_flags.py from the engine's own compile line for
# an src/importdb translation unit. Regenerate when the engine include layout
# changes -- that this list has to track the engine is itself the coupling the
# source-distribution model accepts.

set (CUBRID_ENGINE_INCLUDES
  "${CUBRID_BUILD_DIR}"
  "${CUBRID_SOURCE_DIR}/include"
  "${CUBRID_SOURCE_DIR}/src/api"
  "${CUBRID_SOURCE_DIR}/src/base"
  "${CUBRID_SOURCE_DIR}/src/broker"
  "${CUBRID_SOURCE_DIR}/src/communication"
  "${CUBRID_SOURCE_DIR}/src/compat"
  "${CUBRID_SOURCE_DIR}/src/connection"
  "${CUBRID_SOURCE_DIR}/src/debugging"
  "${CUBRID_SOURCE_DIR}/src/executables"
  "${CUBRID_SOURCE_DIR}/src/heaplayers"
  "${CUBRID_SOURCE_DIR}/src/sp"
  "${CUBRID_SOURCE_DIR}/src/loaddb"
  "${CUBRID_SOURCE_DIR}/src/method"
  "${CUBRID_SOURCE_DIR}/src/monitor"
  "${CUBRID_SOURCE_DIR}/src/object"
  "${CUBRID_SOURCE_DIR}/src/optimizer"
  "${CUBRID_SOURCE_DIR}/src/optimizer/histogram"
  "${CUBRID_SOURCE_DIR}/src/parser"
  "${CUBRID_SOURCE_DIR}/src/replication"
  "${CUBRID_SOURCE_DIR}/src/query"
  "${CUBRID_SOURCE_DIR}/src/session"
  "${CUBRID_SOURCE_DIR}/src/storage"
  "${CUBRID_SOURCE_DIR}/src/thread"
  "${CUBRID_SOURCE_DIR}/src/transaction"
  "${CUBRID_SOURCE_DIR}/src/xasl"
  "${CUBRID_SOURCE_DIR}/src/query/parallel/px_hash_join"
  "${CUBRID_SOURCE_DIR}/src/query/parallel/px_scan"
  "${CUBRID_SOURCE_DIR}/src/query/parallel/px_scan/index"
  "${CUBRID_SOURCE_DIR}/src/query/parallel"
  "${CUBRID_SOURCE_DIR}/src/query/parallel/px_query_execute"
  "${CUBRID_SOURCE_DIR}/cubrid-cci/src/cci"
  "${CUBRID_SOURCE_DIR}/cubrid-cci/src/tools"
  "${CUBRID_BUILD_DIR}/3rdparty/include/expat"
  "${CUBRID_BUILD_DIR}/3rdparty/include/jansson"
  "${CUBRID_BUILD_DIR}/3rdparty/include"
  "${CUBRID_BUILD_DIR}/3rdparty/Source/lz4/lib"
  "${CUBRID_BUILD_DIR}/3rdparty/Source/rapidjson/include"
  "${CUBRID_BUILD_DIR}/3rdparty/Source/re2"
  )

set (CUBRID_ENGINE_DEFINES
  CS_MODE
  GCC
  I386
  LINUX
  MAXPATHLEN=1024
  SYSV
  X86
  _FILE_OFFSET_BITS=64
  _GNU_SOURCE
  _LARGEFILE64_SOURCE
  _REENTRANT
  NDEBUG
  NDEBUG
  )
